package com.example.room

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.lang.reflect.Constructor
import java.util.*

@Entity(tableName = "contact")
data class ContactsEntity(

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name="Id")val id : Int,                          // id is primary key

    @ColumnInfo(name="Name")val name : String,
    @ColumnInfo(name="Age")val age : Int,
    @ColumnInfo(name = "Date")val date : Date,
    val number : Int

){
    constructor(name : String, age :Int, date : Date, number : Int) : this(0, name, age, date, number)     // We can use this if we don't pass id as id is autogenerated
}
